import { useEffect, useState } from "react";
import Head from "next/head";
import { api } from "~/utils/api";
import TweetItem from "~/components/TweetItem";
import { type RouterOutputs } from "~/utils/api";
type Tweets = RouterOutputs["tweet"]["all"];

export default function Home() {
  const { data } = api.tweet.all.useQuery<Tweets>();
  const [tweets, setTweets] = useState<Tweets>([]);

  api.tweet.onUpdate.useSubscription(undefined, {
    onData(tweet) {
      setTweets((prev) => [tweet, ...prev]);
    },
  });

  useEffect(() => {
    if (data) {
      setTweets(data);
    }
  }, [data]);

  return (
    <>
      <Head>
        <title>My T3 Twitter Lite</title>
        <meta
          name="description"
          content="Very lite Twitter-ish app generated by create-t3-app"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="container mx-auto px-4 py-16">
        <div className="mt-8 flex w-full flex-col items-center gap-4">
          {tweets ? (
            tweets.length === 0 ? (
              <p className="text-2xl text-blue-700">No tweets found</p>
            ) : (
              <>
                {tweets.map((tweet) => (
                  <TweetItem tweet={tweet} key={tweet.id} />
                ))}
              </>
            )
          ) : (
            <p className="text-2xl text-blue-700">Loading...</p>
          )}
        </div>
      </div>
    </>
  );
}
